### ISSUE TITLE
Links don't work

### ISSUE THREAD

**Issue by justinjsmith** [opencontrol/opencontrol-website#30]
OpenControl.org links to https://compliance.cloud.gov which has bad links. 

https://compliance.cloud.gov/standards/NIST-800-53-AC-2%201.md returns a 404.

**Comment by brittag** [comment]
Hi @justinjsmith! Thanks for the report, good catch. I'm going to file this as an issue in https://github.com/18F/cg-compliance/issues (and close this one) since this is a problem with that site instead of a problem with the OpenControl site. I work on the cloud.gov team, and we're currently not maintaining/updating the compliance.cloud.gov site, but we hope to get back to it in the future.
